### ISSUE TITLE
Which versions of active_model_serializers will be supported?

### ISSUE THREAD

**Issue by givanse** [hhff/spree_ams#26]
`2-4-alpha` installs

```
'active_model_serializers', '~> 0.8.2'
```

I think that `3-0-alpha` should install

```
'active_model_serializers', '~> 0.9.3'
```

I tried to just bump it in `spree_ams.gemspec` but things broke, not surprised though.

**Comment by hhff** [comment]
why does 3-0-alpha need 0.9.3 ?  The 0.9.x track of AMS is notoriously wacky

the 0.8.x track is the most stable of AMS tracks.  I plan to support JSON API via the 0.10.x track when it hits its first release.

hx

**Comment by givanse** [comment]
Yeah, I imagined you would make the jump to JSON API :+1: 

Just noticed that there is already an RC v2 for `0.10` so probably it will be best to just completely skip `0.9`.

**Comment by hhff** [comment]
yup def.  You can probably try the 0.10.rc with the flat payload AMS adapter - i'd say that should work!

Stuff with blow up if you use the AMS jsonapi adapter tho...
